// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.pablog.model;

import java.math.BigInteger;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.pablog.model.BookDataOnDemand;
import org.pablog.model.BookIntegrationTest;
import org.pablog.repositories.BookRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect BookIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BookIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BookIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    BookDataOnDemand BookIntegrationTest.dod;
    
    @Autowired
    BookRepository BookIntegrationTest.bookRepository;
    
    @Test
    public void BookIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Book' failed to initialize correctly", dod.getRandomBook());
        long count = bookRepository.count();
        Assert.assertTrue("Counter for 'Book' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BookIntegrationTest.testFind() {
        Book obj = dod.getRandomBook();
        Assert.assertNotNull("Data on demand for 'Book' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Book' failed to provide an identifier", id);
        obj = bookRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Book' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Book' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BookIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Book' failed to initialize correctly", dod.getRandomBook());
        long count = bookRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Book', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Book> result = bookRepository.findAll();
        Assert.assertNotNull("Find all method for 'Book' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Book' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BookIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Book' failed to initialize correctly", dod.getRandomBook());
        long count = bookRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Book> result = bookRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Book' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Book' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BookIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Book' failed to initialize correctly", dod.getRandomBook());
        Book obj = dod.getNewTransientBook(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Book' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Book' identifier to be null", obj.getId());
        try {
            bookRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        Assert.assertNotNull("Expected 'Book' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BookIntegrationTest.testDelete() {
        Book obj = dod.getRandomBook();
        Assert.assertNotNull("Data on demand for 'Book' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Book' failed to provide an identifier", id);
        obj = bookRepository.findOne(id);
        bookRepository.delete(obj);
        Assert.assertNull("Failed to remove 'Book' with identifier '" + id + "'", bookRepository.findOne(id));
    }
    
}
